### ISSUE TITLE
Unable to develop without gs storage plugin and shared fs bug

### ISSUE THREAD

**Issue by vsoch** [snakemake/snakemake-executor-plugin-googlebatch#3]
Even when I set that there is a shared filesystem:

```

# Required:
# Common settings shared by various executors.
common_settings = CommonSettings(
    pass_envvar_declarations_to_cmd=True,
    # This will eventually need to be True
    non_local_exec=True,
    implies_no_shared_fs=False,
)
```
(and I've messed with non_local_exec too) with the most recent pull from snakemake, no matter what I do, I cannot run anything:

```
$ snakemake --jobs 1 --executor googlebatch --googlebatch-bucket snakemake-cache-dinosaur --googlebatch-snippets intel-mpi 
Error: If no shared filesystem is assumed, a default storage provider has to be set.
```
I'm not able to use Google Storage (no plugin) and I don't have access to other backends, so I'm not able to develop further. @johanneskoester this is blocking for me. I spent a big chunk of today trying to figure out the storage plugin but I was not successful - I don't totally understand the design.

**Comment by vsoch** [comment]
When I set to s3 I get another error:

```
$ snakemake --jobs 1 --executor googlebatch --googlebatch-bucket snakemake-cache-dinosaur --googlebatch-snippets intel-mpi  --default-storage-provider s3
Traceback (most recent call last):
  File "/home/vanessa/Desktop/Code/snek/snakemake/snakemake/cli.py", line 1862, in args_to_api
    dag_api = workflow_api.dag(
              ^^^^^^^^^^^^^^^^^
  File "/home/vanessa/Desktop/Code/snek/snakemake/snakemake/api.py", line 287, in dag
    return DAGApi(
           ^^^^^^^
  File "<string>", line 6, in __init__
  File "/home/vanessa/Desktop/Code/snek/snakemake/snakemake/api.py", line 382, in __post_init__
    self.workflow_api._workflow.dag_settings = self.dag_settings
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vanessa/Desktop/Code/snek/snakemake/snakemake/api.py", line 333, in _workflow
    workflow.include(
  File "/home/vanessa/Desktop/Code/snek/snakemake/snakemake/workflow.py", line 1320, in include
    exec(compile(code, snakefile.get_path_or_uri(), "exec"), self.globals)
  File "/home/vanessa/Desktop/Code/snek/snakemake-executor-plugin-googlebatch/example/hello-world-intel-mpi/Snakefile", line 3, in <module>
    rule all:
  File "/home/vanessa/Desktop/Code/snek/snakemake/snakemake/workflow.py", line 1484, in decorate
    rule.set_input(*ruleinfo.input.paths, **ruleinfo.input.kwpaths)
  File "/home/vanessa/Desktop/Code/snek/snakemake/snakemake/rules.py", line 268, in set_input
    self._set_inoutput_item(item)
  File "/home/vanessa/Desktop/Code/snek/snakemake/snakemake/rules.py", line 512, in _set_inoutput_item
    self._set_inoutput_item(i, output=output)
  File "/home/vanessa/Desktop/Code/snek/snakemake/snakemake/rules.py", line 427, in _set_inoutput_item
    item = self.apply_path_modifier(item, path_modifier, property=property)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vanessa/Desktop/Code/snek/snakemake/snakemake/rules.py", line 362, in apply_path_modifier
    return apply(item)
           ^^^^^^^^^^^
  File "/home/vanessa/Desktop/Code/snek/snakemake/snakemake/path_modifier.py", line 40, in modify
    modified_path = self.apply_default_storage(self.replace_prefix(path, property))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vanessa/Desktop/Code/snek/snakemake/snakemake/path_modifier.py", line 115, in apply_default_storage
    return flag_with_storage_object(path, storage_object)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vanessa/Desktop/Code/snek/snakemake/snakemake/storage.py", line 16, in flag_with_storage_object
    modified = flag(storage_object.local_path(), "storage_object", storage_object)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vanessa/Desktop/Code/snek/snakemake-executor-plugin-googlebatch/env/lib/python3.11/site-packages/snakemake_interface_storage_plugins/storage_object.py", line 90, in local_path
    return self.provider.local_prefix / self.local_suffix()
                                        ^^^^^^^^^^^^^^^^^^^
  File "/home/vanessa/Desktop/Code/snek/snakemake-executor-plugin-googlebatch/env/lib/python3.11/site-packages/snakemake_storage_plugin_s3/__init__.py", line 258, in local_suffix
    return self._local_suffix
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'StorageObject' object has no attribute '_local_suffix'
```

**Comment by vsoch** [comment]
okay just hard coded that boolean, but now a different error:

```
  File "/home/vanessa/Desktop/Code/snek/snakemake-executor-plugin-googlebatch/env/lib/python3.11/site-packages/snakemake_executor_plugin_googlebatch/executor.py", line 139, in get_command_writer
    command = self.format_job_exec(job)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vanessa/Desktop/Code/snek/snakemake-executor-plugin-googlebatch/env/lib/python3.11/site-packages/snakemake_interface_executor_plugins/executors/real.py", line 156, in format_job_exec
    self.get_envvar_declarations(),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vanessa/Desktop/Code/snek/snakemake-executor-plugin-googlebatch/env/lib/python3.11/site-packages/snakemake_interface_executor_plugins/executors/real.py", line 125, in get_envvar_declarations
    return " ".join(f"{var}={repr(value)}" for var, value in self.envvars())
                                                             ^^^^^^^^^^^^^^
  File "/home/vanessa/Desktop/Code/snek/snakemake-executor-plugin-googlebatch/env/lib/python3.11/site-packages/snakemake_interface_executor_plugins/executors/real.py", line 175, in envvars
    return self.workflow.spawned_job_args_factory.envvars()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vanessa/Desktop/Code/snek/snakemake/snakemake/spawn_jobs.py", line 126, in envvars
    envvars.update(self.get_storage_provider_envvars())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vanessa/Desktop/Code/snek/snakemake/snakemake/spawn_jobs.py", line 73, in get_storage_provider_envvars
    return {
           ^
  File "/home/vanessa/Desktop/Code/snek/snakemake/snakemake/spawn_jobs.py", line 74, in <dictcomp>
    plugin.get_envvar(field.name): field_settings
    ^^^^^^^^^^^^^^^^^
AttributeError: 'Plugin' object has no attribute 'get_envvar'
```
I'm going to try checking out the last commit to undo these.

**Comment by vsoch** [comment]
okay I can't figure out what commit to checkout - going to give up for now.

**Comment by johanneskoester** [comment]
Those bugs should all be fixed now (latest main branch of snakemake and latest releases of the plugins and interfaces). In general, have a look at the kubernetes plugin to check how to set up the test suite to run the executor with the S3 Minio play server, which is completely free to use, so that we have less credits being used in the google testing.

**Comment by vsoch** [comment]
These are fixed.
